allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  '@babel/core': 8.0.1
  postcss: 8.5.19
  ws: 8.21.1
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.110.7'
  - '@supabase/functions-js@2.110.7'
  - '@supabase/phoenix@0.4.5'
  - '@supabase/postgrest-js@2.110.7'
  - '@supabase/realtime-js@2.110.7'
  - '@supabase/storage-js@2.110.7'
  - '@supabase/supabase-js@2.110.7'
